### ISSUE TITLE
Extra Variable Definition 

### ISSUE THREAD

**Issue by CJoh-NHD** [NewhavenDisplay/NHD-240128WG-Example#1]
https://github.com/NewhavenDisplay/NHD-240128WG-Example/blob/e5e97dc3b7c48633bb02e38a8fae02876d4be2ab/NHD_240128WG-Example/NHD_240128WG-Example.ino#L310

Variable `j` is defined but not utilized in the following functions:

- [`void dispFill()`](https://github.com/NewhavenDisplay/NHD-240128WG-Example/blob/e5e97dc3b7c48633bb02e38a8fae02876d4be2ab/NHD_240128WG-Example/NHD_240128WG-Example.ino#L308)
- [`void dispClear()`](https://github.com/NewhavenDisplay/NHD-240128WG-Example/blob/e5e97dc3b7c48633bb02e38a8fae02876d4be2ab/NHD_240128WG-Example/NHD_240128WG-Example.ino#L324)
- [`void dispImage()`](https://github.com/NewhavenDisplay/NHD-240128WG-Example/blob/e5e97dc3b7c48633bb02e38a8fae02876d4be2ab/NHD_240128WG-Example/NHD_240128WG-Example.ino#L340)

Please remove variable j definitions from these functions.

**Comment by ZPal-NHD** [comment]
Fixed issue #1
